
services:

  backend:
    build:
        context: ./be-nest
        dockerfile: Dockerfile
    container_name: be-nest
    ports:
      - '3033:3033'
    volumes:
      - ./be-nest/store://usr/src/app/store


  frontend:
    build:
        context: ./fe-nuxt
        dockerfile: Dockerfile
    container_name: fe-nuxt
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - backend